pipelines:
  custom:
    azure:
      - step:
          name: "Build"
          script:
            - nvm install 12
            - npm install
            - npm run build
            - cd build